// export const BASE_URL = process.env.NODE_ENV === 'development ' ? 'http://localhost:5000' : ''
export const BASE_URL = ''
export const PRODUCTS_URL = 'http://localhost:5000/api/products'
export const USERS_URL = '/api/users'
export const ORDER_URL = '/api/order'
export const PAYPAL_URL = 'api/config/paypal'
